kafka:
  addr: kafka:9092
  group: agent-group
  task_topic: tasks
  status_topic: status-updates
data-provider:
  addr: "127.0.0.1:8083"
  useTLS: false
  grpcServerName: ""
agent:
  grpc:
    network: "tcp"
    addr: "0.0.0.0:8082"
    useTLS: false
    cert: ""
    key: ""
    ca: ""
grpc-client:
  caCert: ""
  clientCert: ""
  clientKey: ""