version: '3.8'

networks:
  kafka-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_JVMFLAGS: "-Xmx2g -Xms2g" # Allocate 2GB heap memory
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  agent-service:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: agent-service
    depends_on:
      - kafka
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./config.yaml:/etc/agent-service/config.yaml
    networks:
      - kafka-network

  mock-api:
    build:
      context: ../mock1
      dockerfile: ./Dockerfile
    container_name: mock-api
    ports:
      - "8083:8083"
    networks:
      - kafka-network
